name: Deploy Serenity Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Serenity Report"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Serenity Report
      uses: actions/download-artifact@v4
      with:
        name: serenity-report
        path: ./target/site/serenity

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/serenity

