name: Generate Serenity Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Check Maven Version
      run: mvn -version
    - name: Checking Gherkin feature files
      run: mvn serenity:check-gherkin  
    - name: Set up Chrome
      run: sudo apt-get install -y google-chrome-stable
    - name: Set up Xvfb
      run: |
        sudo apt-get install -y xvfb
        Xvfb :99 -ac &
        export DISPLAY=:99
    - name: Run Tests
      run: mvn clean verify -Dwebdriver.chrome.options="--headless --no-sandbox --disable-dev-shm-usage"
      env:
        DISPLAY: :99
    - name: Upload Serenity Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: serenity-report
        path: ./target/site/serenity


