name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Check Maven Version
      run: mvn -version
    - name: Checking Gherkin feature files
      run: mvn serenity:check-gherkin  
    - name: Run Dependency Check
      run: mvn dependency-check:check -X


